
export const GET_RECENT_ADDED_BOOK_REQUEST = 'GET_RECENT_ADDED_BOOK_REQUEST';
export const GET_RECENT_ADDED_BOOK_SUCCESS = 'GET_RECENT_ADDED_BOOK_SUCCESS';
export const GET_RECENT_ADDED_BOOK_FAILURE = 'GET_RECENT_ADDED_BOOK_FAILURE';


